### ISSUE TITLE
python/30-seconds-of-python

### ISSUE THREAD

**Issue by huhuhang** [labex-labs/open-source-challenges#16]

**Comment by himanshugupta11002** [comment]
can you explain the issue in detail so I'll start working on this issue

**Comment by huhuhang** [comment]
This is an `index.json` that requires adding `SKILL_ID`,  each step may contain multiple IDs.

https://github.com/labex-labs/open-source-challenges/blob/master/linux/30-bash-scripts/lab-get-arguments-from-command-line/index.json

You can learn more at https://www.labex.wiki/advanced/skill-tree
